export const RENDER_AVATARS = {
  male1: require("@/assets/images/user-avatars/male-1.png"),
  female1: require("@/assets/images/user-avatars/female-1.png"),
  male2: "/user-avatars/male-2.png",
  female2: "/user-avatars/female-2.png",
  male3: "/user-avatars/male-3.png",
  female3: "/user-avatars/female-3.png",
  limited1: "/user-avatars/limited-1.png",
  limited2: "/user-avatars/limited-2.png",
  limited3: "/user-avatars/limited-3.png",
  limited4: "/user-avatars/limited-4.png",
  limited5: "/user-avatars/limited-5.png",
  limited6: "/user-avatars/limited-6.png",
};

export const AVATARS = {
  male1: "/user-avatars/male-1.png",
  female1: "/user-avatars/female-1.png",
  male2: "/user-avatars/male-2.png",
  female2: "/user-avatars/female-2.png",
  male3: "/user-avatars/male-3.png",
  female3: "/user-avatars/female-3.png",
  limited1: "/user-avatars/limited-1.png",
  limited2: "/user-avatars/limited-2.png",
  limited3: "/user-avatars/limited-3.png",
  limited4: "/user-avatars/limited-4.png",
  limited5: "/user-avatars/limited-5.png",
  limited6: "/user-avatars/limited-6.png",
}

export const FRAMES = {
  def: "def",
  black: "black",
  white: "white",
  gray: "gray",
  green: "green",
  blue: "blue",
  lightBlue: "lightBlue",
  orange: "orange",
  purple: "purple",
  red: "red",
  yellow: "yellow",
  pink: "pink",
  teal: "teal",
  lime: "lime",
  indigo: "indigo",
  rose: "rose",
  amber: "amber",
  cyan: "cyan",
  emerald: "emerald",
  violet: "violet",
};

export const BACKGROUNDS = {
  def: "/backgrounds/cover-10.jpg",
  cover1: "/backgrounds/cover-2.jpg",
  cover2: "/backgrounds/cover-3.jpg",
  cover3: "/backgrounds/cover-4.jpg",
  cover4: "/backgrounds/cover-5.jpg",
  cover5: "/backgrounds/cover-6.jpg",
  cover6: "/backgrounds/cover-7.jpg",
  cover7: "/backgrounds/cover-8.jpg",
  cover8: "/backgrounds/cover-9.jpg",
  cover9: "/backgrounds/cover-1.jpg",
};

